### ISSUE TITLE
Playback Errors

### ISSUE THREAD

**Issue by mdorchain** [vmirage/TMDBTrailer.bundle#1]
The api works perfectly how ever all the trailers are triggering Playback errors: "An error occurred trying to play "Movie Title | Official Trailer HD | A24". Am I missing anything? Tnx.

**Comment by mdorchain** [comment]
This seems to fix the issue: https://forums.plex.tv/t/traileraddict-plugin-stopped-working-about-2-weeks-ago/374258/24

**Comment by vmirage** [comment]
Try installing another YouTube plugin. The preinstall YouTube plugin doesn't doesn't handle YouTube well.

https://github.com/kolsys/YouTubeTV.bundle
