### ISSUE TITLE
“Playback Error” and “Error code: s1001 (Network)”.

### ISSUE THREAD

**Issue by bobbintb** [vmirage/TMDBTrailer.bundle#3]
Any way to prioritize what trailer is the main trailer to play? I have an example movie with 3 trailers and 2 teasers (according to TMDB) but Plex plays one of the teasers by default instead of the theatrical trailers. I tried playing with the settings Add Trailers, Add Feature Trailers, and Add Theatrical Trailers but it seems to see them ass as "Add Trailers".

**Comment by Seidel76** [comment]
I've the problem too... Do you resolve it ?

**Comment by vmirage** [comment]
Unfortunately there is no way to sort them. Video is added in the order it was given by TMDB. The only solution I could think of is to make the code smart enough to parse the text in the title and reorder them. Anyone interested could update the code and I'll add them in. The code might need to be aware of title in other languages as well.

**Comment by vmirage** [comment]
Sorry. my bad. I didn't realize I'm also including clip and teaser type into the trailer. I think this should be fixable.

**Comment by vmirage** [comment]
Fixed in v4.2
