### ISSUE TITLE
error code: s1001 (network)

### ISSUE THREAD

**Issue by IIeTp** [vmirage/TMDBTrailer.bundle#4]
Hi, I have installed the plugin version 4.2 and the current youtube plugin.
trailers are not playable. here are the logs.
[com.plexapp.agents.tmdbtrailer.log](https://github.com/vmirage/TMDBTrailer.bundle/files/4785500/com.plexapp.agents.tmdbtrailer.log)

can you tell me what is the reason?

**Comment by vmirage** [comment]
The error seems to be related to YoutubeTV.bundle. Maybe open an issue there?

**Comment by IIeTp** [comment]
i have the same output, even without youtubetv.
this is strange, everything worked before. If after the update no one has errors, I’ll try to figure it out on my own, thanks.
